export const BUSINESS = {
  name: "pH Prescription",
  tagline: "Water That Works for Your Health",
  phone: "772-220-8789",
  phoneTollFree: "888-728-2783",
  phoneEmergency: "772-201-2929",
  email: "info@phprescription.com",
  emailAquapellis: "info@aquapellis.com",
  address: {
    street: "3210 SW 42nd Ave",
    city: "Palm City",
    state: "FL",
    zip: "34990",
    full: "3210 SW 42nd Ave, Palm City, FL 34990",
  },
  url: "https://phprescription.com",
  founded: "2005",
  founderName: "Leo Szymborski",
  warehouseSqFt: "10,000",
  yearsExperience: "40+",
  certifications: ["WQA Certified", "Made in USA"],
  social: {
    facebook: "",
    youtube: "",
  },
} as const;

export const PRODUCTS = [
  {
    name: "Ultimate Purified Drinking System",
    sku: "pH-RO-1100",
    price: "$1,747.00",
    badge: "#1 Doctor Recommended",
    description: "Our flagship under-sink reverse osmosis drinking system. Multi-phase reverse osmosis with re-mineralization. Removes up to 99% of toxins, re-mineralizes, and infuses molecular hydrogen for antioxidant-rich drinking water.",
    slug: "ultimate-purified-drinking-system",
  },
  {
    name: "Finely Filtered Compact Drinking System",
    sku: "pH-UC-700",
    price: "$985.00",
    badge: "Most Popular",
    description: "Experience our best value in finely filtered water with antioxidant and energizing benefits in a compact yet powerful under-counter model that filters and mineralizes water, reducing up to 99% of chemicals like chlorine, chloramines, fluoride, heavy metals and many other toxins.",
    slug: "compact-drinking-system",
  },
  {
    name: "Total Home Premier",
    sku: "pH-WH-3500-CO",
    price: "$9,244.25",
    badge: "Whole Home",
    description: "Prevent unwanted toxins and impurities before they enter your home with our twin-tank high-capacity Total Home Multi-Phase Enhanced Finely Filtered Water System. This 2-Part System extends health and wellness for your family and keeps water lines to appliances clean.",
    slug: "total-home-system",
  },
  {
    name: "Total Home Grande High Capacity",
    sku: "pH-WH-5500",
    price: "$12,197.00",
    badge: "High Capacity",
    description: "Recommended for homes with up to 7 bathrooms. Prevents toxins and impurities with 2 million gallon capability. Extend your family's health and wellness as well as the cleanliness of water lines to all your taps and appliances.",
    slug: "total-home-grande",
  },
  {
    name: "NEW Hydro-Clean Shower Filter",
    sku: "pH-SF-OH",
    price: "$81.00",
    badge: "Shower",
    description: "Sleek lightweight design with powerful proprietary filtering media with Chlorigone™ — 100x more effective at removing Chlorine, Chloramines, lead, mercury, cadmium, aluminum and many other heavy metals. Fits most overhead showers and hand-held shower systems.",
    slug: "hydro-clean-shower-filter",
  },
  {
    name: "Total Business Paddle-Touch Hot/Cold",
    sku: "WC-PP-6",
    price: "$2,613.60 – $3,484.80",
    badge: "Commercial",
    description: "High-capacity hot/cold water cooler with paddle-touch dispensing for offices, restaurants, and facilities. 80 lbs, 14 x 14 x 48 in. Lease and finance options available.",
    slug: "business-water-cooler",
  },
] as const;

export type Product = {
  name: string;
  sku: string;
  price: string;
  badge: string;
  description: string;
  category: string;
  image: string;
  slug: string;
};

export const PRODUCTS_ALL: Product[] = [
  // Drinking Systems
  {
    name: "Ultimate Purified Drinking System",
    sku: "pH-RO-1100",
    price: "$1,747.00",
    badge: "Drinking Systems",
    description: "Multi-phase reverse osmosis with re-mineralization. Removes up to 99% of toxins, restructures water, and infuses molecular hydrogen for antioxidant-rich drinking water.",
    category: "Drinking Systems",
    image: "https://phprescription.com/wp-content/uploads/2020/12/TW56095-600.jpg",
    slug: "ultimate-purified-drinking-system",
  },
  {
    name: "Finely Filtered Compact Drinking System",
    sku: "pH-UC-700",
    price: "$985.00",
    badge: "Drinking Systems",
    description: "Best value in finely filtered water with antioxidant and energizing benefits. Compact under-counter model reduces up to 99% of chemicals like chlorine, chloramines, fluoride, heavy metals and other toxins.",
    category: "Drinking Systems",
    image: "https://phprescription.com/wp-content/uploads/2020/12/pHUC-700-full-size-600x600.jpg",
    slug: "compact-drinking-system",
  },
  {
    name: "Alkaline Water Filtration",
    sku: "pH-RO-1100-LF-CY",
    price: "$1,375.00",
    badge: "Drinking Systems",
    description: "Premium alkaline water filtration system with lead-free faucet. Multi-stage reverse osmosis with alkaline re-mineralization.",
    category: "Drinking Systems",
    image: "https://phprescription.com/wp-content/uploads/2020/12/TW56095-600.jpg",
    slug: "alkaline-water-filtration",
  },
  {
    name: "MD Drinking Water",
    sku: "",
    price: "Call for pricing",
    badge: "Drinking Systems",
    description: "Medical-grade drinking water system engineered for clinical purity standards. Advanced multi-stage filtration for medical and high-purity applications.",
    category: "Drinking Systems",
    image: "https://phprescription.com/wp-content/uploads/2021/01/water-square.jpg",
    slug: "md-drinking-water",
  },
  {
    name: "Ultimate PurifiedRestructured Drinking System Filter",
    sku: "UC-F-56",
    price: "$412.50",
    badge: "Drinking Systems",
    description: "Replacement filter for the Doctor Recommended System — the only filter that simultaneously provides alkalinity, hydrogen and critical mineral replacement for optimum taste and quality.",
    category: "Drinking Systems",
    image: "https://phprescription.com/wp-content/uploads/2020/12/pH-UC-56-600x384.jpg",
    slug: "ultimate-purified-restructured-drinking-system-filter",
  },
  {
    name: "Ultimate Purified Multi-Phase Drinking System Filter",
    sku: "UC-F-123",
    price: "$110.00",
    badge: "Drinking Systems",
    description: "Replacement filter — tri-integrated cartridge with 5-micron sediment filtration, Granular Activated Carbon, and Carbon Block to maintain efficiency of your Ultimate Purified Multi-Phase Drinking System.",
    category: "Drinking Systems",
    image: "https://phprescription.com/wp-content/uploads/2020/12/pHRO-1100-UC123-full-size-600x600.jpg",
    slug: "ultimate-purified-multi-phase-drinking-system-filter",
  },
  // Total Home
  {
    name: "Total Home Premier",
    sku: "pH-WH-3500-CO",
    price: "$9,244.25",
    badge: "Total Home",
    description: "Twin-tank high-capacity Total Home Multi-Phase Enhanced Finely Filtered Water System + Ultimate Purified Drinking System. Extends health and wellness for your family and keeps water lines clean.",
    category: "Total Home",
    image: "https://phprescription.com/wp-content/uploads/2021/05/pH-WH-3500-CO-v2.jpg",
    slug: "total-home-premier",
  },
  {
    name: "Total Home Premier+",
    sku: "pH-WH-3500-CO+",
    price: "$10,003.25",
    badge: "Total Home",
    description: "Our premium whole-home package with enhanced features. Comprehensive whole-home water restructuring for every tap, every shower, every glass of water.",
    category: "Total Home",
    image: "https://phprescription.com/wp-content/uploads/slider27/total-home-premier-plus-main-with-charger.png",
    slug: "total-home-premier-plus",
  },
  {
    name: "Total Home Optimum Restructured Water System",
    sku: "pH-WH-3500",
    price: "$8,020.75",
    badge: "Total Home",
    description: "Drinking, cooking, bathing and daily care rituals become a wellness experience. Naturally reduces harmful chemicals while creating beneficial finely filtered spring quality water from every tap.",
    category: "Total Home",
    image: "https://phprescription.com/wp-content/uploads/2020/12/pH-WH-3500-WMS-600x900.jpg",
    slug: "total-home-optimum-restructured-water-system",
  },
  {
    name: "Total Home Grande High Capacity Water System",
    sku: "pH-WH-5500",
    price: "$12,197.00",
    badge: "Total Home",
    description: "Recommended for homes with up to 7 bathrooms. 2 million gallon capability. Extends health and wellness as well as cleanliness of water lines to all taps and appliances.",
    category: "Total Home",
    image: "https://phprescription.com/wp-content/uploads/2020/12/ph-WH-5500.jpg",
    slug: "total-home-grande",
  },
  {
    name: "Total Home WMS QuadVortex System",
    sku: "pH-WMS-900",
    price: "$2,407.75",
    badge: "Total Home",
    description: "Innovative Environmental system. Provides micro-clustered/structured energized water with Fibonacci-designed quadruple vortex system using rare earth magnets. Recommended for use with all Total Home systems.",
    category: "Total Home",
    image: "https://phprescription.com/wp-content/uploads/2020/12/pH-WMS-900-CO-tank-v2-600x600.jpg",
    slug: "total-home-wms-quadvortex-system",
  },
  {
    name: "Total Home WMS QuadVortex PLUS",
    sku: "pH-WMS-900-CO",
    price: "$3,303.25",
    badge: "Total Home",
    description: "Fibonacci-designed with four vortices and twelve rare earth magnets. Paired with premium Total Home Toxin Reducer PLUS filtration system for finely filtered spring-quality water from every tap.",
    category: "Total Home",
    image: "https://phprescription.com/wp-content/uploads/2020/12/pH-WMS-900-CO-v4-600x600.jpg",
    slug: "total-home-wms-quadvortex-plus",
  },
  {
    name: "Total Home Water Treatment System",
    sku: "pH-WH-2700",
    price: "$5,075.75",
    badge: "Total Home",
    description: "Ideal for handling minerals like calcium, magnesium, manganese, iron and heavy metals. Filters up to 99% of chlorine, pesticides, herbicides, VOCs, THMs, PFAS/Forever Plastics through natural media blends.",
    category: "Total Home",
    image: "https://phprescription.com/wp-content/uploads/2020/12/pH-wh-2700.jpg",
    slug: "total-home-water-treatment-system",
  },
  {
    name: "Total Home Toxin Reducer PLUS",
    sku: "pH-WH-2000",
    price: "$4,701.00",
    badge: "Total Home",
    description: "Reduces fluoride and filters up to 99% of chlorine, heavy metals, pesticides, herbicides, VOCs, THMs, PFAS/Forever Plastics through Brimac Carbon and KDF 55 media.",
    category: "Total Home",
    image: "https://phprescription.com/wp-content/uploads/2020/12/pH-WH-2000-600x600.jpg",
    slug: "total-home-toxin-reducer-plus",
  },
  {
    name: "Total Home Toxin Reducer Filters VOCs",
    sku: "pH-WH-1500",
    price: "$4,065.75",
    badge: "Total Home",
    description: "Reduces chlorine, volatile organic compounds and more. Multi-stage natural media filtration for comprehensive whole-home water treatment.",
    category: "Total Home",
    image: "https://phprescription.com/wp-content/uploads/2020/12/pH-WH-2000-600x600.jpg",
    slug: "total-home-toxin-reducer-filters-vocs",
  },
  {
    name: "Total Home Toxin and Water Hardness Reduction System",
    sku: "pH-WH-4700",
    price: "$9,141.25",
    badge: "Total Home",
    description: "Double-duty system reduces fluoride and filters up to 99% of chlorine, chloramine, heavy metals, pesticides, herbicides, VOCs and THMs while handling hard minerals.",
    category: "Total Home",
    image: "https://phprescription.com/wp-content/uploads/2022/03/pH-WH-4700-600x600.jpg",
    slug: "total-home-toxin-and-water-hardness-reduction-system",
  },
  {
    name: "Best Whole House Water Filtration System",
    sku: "pH-WH-3500-WMS-900",
    price: "$2,084.50",
    badge: "Total Home",
    description: "Comprehensive whole-house filtration with QuadVortex technology. Quality water system for every tap in your home.",
    category: "Total Home",
    image: "https://phprescription.com/wp-content/uploads/2021/05/pH-WH-3500-CO-v2.jpg",
    slug: "best-whole-house-water-filtration-system",
  },
  {
    name: "Total Home Charger UV Water Disinfection System",
    sku: "pH-CWUV5/6-15C",
    price: "$1,445.95",
    badge: "Total Home",
    description: "Powerful UV disinfection for rates up to 15 gallons per minute. Controls bacteria, viruses, E-coli, cysts, spores, Cryptosporidium and Giardia lamblia with long-lasting performance.",
    category: "Total Home",
    image: "https://phprescription.com/wp-content/uploads/2025/02/pH-CWUV5-6-15C-product-img-600x600.png",
    slug: "total-home-charger-uv-water-disinfection-system",
  },
  // UV & Disinfection
  {
    name: "Anti-Microbial Filtration with UV Sterilization",
    sku: "pH-UV-370",
    price: "$413.00",
    badge: "UV & Disinfection",
    description: "Disinfection and micro-organism protection to 0.5ppm including bacteria, E-coli, Cysts, Spores, Viruses, VOCs, THMs, chloramines with 9000 hours of use.",
    category: "UV & Disinfection",
    image: "https://phprescription.com/wp-content/uploads/2020/12/pH-UV-370-full-size-600x600.jpg",
    slug: "anti-microbial-filtration-with-uv-sterilization",
  },
  {
    name: "Polaris Disinfection System",
    sku: "UVA-1C-UV",
    price: "$125.75",
    badge: "UV & Disinfection",
    description: "Developed to laboratory standard of eliminating micro-organisms. Applicable for multiple industries from medical to cosmetic to food to pharmaceutical and more.",
    category: "UV & Disinfection",
    image: "https://phprescription.com/wp-content/uploads/2020/12/Polaris-UVA-1C-full-size-600x512.jpg",
    slug: "polaris-disinfection-system",
  },
  {
    name: "Drinking System Polaris UV Quartz Sleeve Replacement",
    sku: "pH-2510",
    price: "$32.14",
    badge: "UV & Disinfection",
    description: "Replacement quartz sleeve for Polaris Scientific UVA-1C ultraviolet sterilization system. 245mm, made for the GI1OPP 10W UV Lamp.",
    category: "UV & Disinfection",
    image: "https://phprescription.com/wp-content/uploads/2023/05/polaris-uv-sleeve-replacement.jpg",
    slug: "drinking-system-polaris-uv-quartz-sleeve-replacement",
  },
  {
    name: "Drinking System Polaris UV Transformer Replacement",
    sku: "pH-BEB1024",
    price: "$67.32",
    badge: "UV & Disinfection",
    description: "Replacement transformer for the UVA Disinfection Drinking System. Accepts 100VAC or 200VAC input. Developed to laboratory standard.",
    category: "UV & Disinfection",
    image: "https://phprescription.com/wp-content/uploads/2023/05/polaris-transformer-replacement.jpg",
    slug: "drinking-system-polaris-uv-transformer-replacement",
  },
  {
    name: "Drinking System Polaris UV Lamp Replacement",
    sku: "pH-GI1OPP",
    price: "$43.32",
    badge: "UV & Disinfection",
    description: "Annual UV lamp replacement for proper disinfection function. Install authentic Replacement Lamps to ensure system performance and efficiency.",
    category: "UV & Disinfection",
    image: "https://phprescription.com/wp-content/uploads/2023/05/polaris-uv-lamp-replacement-prongs.jpg",
    slug: "drinking-system-polaris-uv-lamp-replacement",
  },
  {
    name: "Total Home UV Water Disinfection System Viqua Transformer Replacement",
    sku: "pH-BAICECL",
    price: "$427.00",
    badge: "UV & Disinfection",
    description: "Electronic ballast for the Total Home UV Water Disinfection System pH-UV-410. Features visual power indicator, audible lamp failure alert, lamp replacement reminder.",
    category: "UV & Disinfection",
    image: "https://phprescription.com/wp-content/uploads/2023/05/viqua-power-pack.jpg",
    slug: "total-home-uv-viqua-transformer-replacement",
  },
  {
    name: "Total Home UV Water Disinfection System Viqua Lamp Replacement",
    sku: "pH-S410RL-ho",
    price: "$194.82",
    badge: "UV & Disinfection",
    description: "Annual UV lamp replacement for proper disinfection. Install authentic Replacement Lamps to ensure proper system performance and efficiency.",
    category: "UV & Disinfection",
    image: "https://phprescription.com/wp-content/uploads/2023/05/viqua-lamp-tube.jpg",
    slug: "total-home-uv-viqua-lamp-replacement",
  },
  {
    name: "Total Home UV Water Disinfection System Viqua Quartz Sleeve Replacement",
    sku: "pH-QS410",
    price: "$101.50",
    badge: "UV & Disinfection",
    description: "Compatible replacement quartz sleeve for Total Home UV Water Disinfection System pH-UV-410. Double open-ended quartz sleeve shipped with two o-rings.",
    category: "UV & Disinfection",
    image: "https://phprescription.com/wp-content/uploads/2023/05/viqua-sleeve.jpg",
    slug: "total-home-uv-viqua-quartz-sleeve-replacement",
  },
  // Showers & Tubs
  {
    name: "NEW Hydro-Clean Shower Filter",
    sku: "pH-SF-OH",
    price: "$81.00",
    badge: "Showers & Tubs",
    description: "Sleek lightweight design with Chlorigone™ filtering media — 100x more effective at removing Chlorine, Chloramines, lead, mercury, cadmium, aluminum and heavy metals. Fits most overhead and hand-held shower systems.",
    category: "Showers & Tubs",
    image: "https://phprescription.com/wp-content/uploads/slider8/hydro-filter-slide-v2.jpeg",
    slug: "hydro-clean-shower-filter",
  },
  {
    name: "NEW Hydro-Clean HandHeld Shower",
    sku: "pH-SF-HH",
    price: "$172.25",
    badge: "Showers & Tubs",
    description: "Hand-held shower system with Chlorigone™ filtering media — 100x more effective at removing Chlorine, Chloramines, lead, mercury, cadmium, aluminum and heavy metals. Hybrid filtration controls bacteria, algae, fungi and scale.",
    category: "Showers & Tubs",
    image: "https://phprescription.com/wp-content/uploads/slider8/hydro-handheld-hero-v3.jpeg",
    slug: "hydro-clean-handheld-shower",
  },
  {
    name: "Pneuma Genesis HDO Warm/Cold Soaking Tub",
    sku: "pH-PG-HDO-WC",
    price: "Call for pricing",
    badge: "Showers & Tubs",
    description: "Nearly 10 years of research, breakthrough in Life Sciences. Proprietary Hyper Dissolved Oxygen (HDO) technology creates billions of oxygen nano-bubbles for detox, reset, improved healing and energy. 72x48x27 in.",
    category: "Showers & Tubs",
    image: "https://phprescription.com/wp-content/uploads/2024/06/pneuma-tub-hero.jpg",
    slug: "pneuma-genesis-hdo-warm-cold-soaking-tub",
  },
  {
    name: "Pneuma Genesis HDO Warm Recovery Soaking Tub",
    sku: "pH-PG-HDO-W",
    price: "Call for pricing",
    badge: "Showers & Tubs",
    description: "HDO technology creates billions of nano-bubbles in a warm soaking tub allowing the dermis and epidermis to absorb increased oxygen into red blood cells for healing and repair. 72x48x27 in.",
    category: "Showers & Tubs",
    image: "https://phprescription.com/wp-content/uploads/2024/06/pneuma-tub-hero.jpg",
    slug: "pneuma-genesis-hdo-warm-recovery-soaking-tub",
  },
  // Nutraceuticals
  {
    name: "N101 Nitric Oxide Lozenges",
    sku: "pH-N101",
    price: "$79.99",
    badge: "Nutraceuticals",
    description: "Nitric oxide support in convenient lozenge form. Gluten-free, GMO-free, all-natural. Supports cardiovascular health and cellular energy.",
    category: "Nutraceuticals",
    image: "https://phprescription.com/wp-content/uploads/2024/07/N1o1-Lozenge-hero.jpg",
    slug: "n101-nitric-oxide-lozenges",
  },
  {
    name: "N.O. Beetz Nitric Oxide Infusion Sticks",
    sku: "pH-NOB",
    price: "$79.99",
    badge: "Nutraceuticals",
    description: "Backed by 20+ years of research from Dr. Nathan Bryan, the first to discover natural chemistry for Nitric Oxide production. Most powerful Nitric Oxide enhancer available. Mix one packet in 2-3 oz finely filtered water daily.",
    category: "Nutraceuticals",
    image: "https://phprescription.com/wp-content/uploads/2024/06/no-beetz-hero.jpg",
    slug: "no-beetz-nitric-oxide-infusion-sticks",
  },
  // Faucets
  {
    name: "Lead-Free Countertop Faucet Elegant",
    sku: "LF-E-1",
    price: "$105.00",
    badge: "Faucets",
    description: "Lead-free countertop faucet in elegant design. 5x1.5x14 in, 2 lbs. Compatible with pH Prescription drinking systems.",
    category: "Faucets",
    image: "https://phprescription.com/wp-content/uploads/2021/01/TW55708-600x900.jpg",
    slug: "lead-free-countertop-faucet-elegant",
  },
  {
    name: "Lead-Free Countertop Faucet Contemporary Copper",
    sku: "LF-4",
    price: "$105.00",
    badge: "Faucets",
    description: "Lead-free countertop faucet in contemporary copper finish. 5x1.5x14 in, 2 lbs. Stylish upgrade for your pH Prescription drinking system.",
    category: "Faucets",
    image: "https://phprescription.com/wp-content/uploads/2021/04/TW55747-600.jpg",
    slug: "lead-free-countertop-faucet-contemporary-copper",
  },
  {
    name: "Lead-Free Countertop Faucet Contemporary",
    sku: "LF-CY-1",
    price: "$105.00",
    badge: "Faucets",
    description: "Lead-free countertop faucet in contemporary design. 7x1.5x14 in, 2 lbs. Clean modern lines for any kitchen aesthetic.",
    category: "Faucets",
    image: "https://phprescription.com/wp-content/uploads/2021/01/TW55678-600x764.jpg",
    slug: "lead-free-countertop-faucet-contemporary",
  },
  // Testing Equipment
  {
    name: "ORP Water Test Meter",
    sku: "pH-MW-500",
    price: "$163.35",
    badge: "Testing Equipment",
    description: "Portable ORP meter for Educational, Agriculture, Horticulture, water and environmental analysis. 5x1x6 in, 2 lbs.",
    category: "Testing Equipment",
    image: "https://phprescription.com/wp-content/uploads/2020/12/pH-orp-meter-MW500-full-size.jpg",
    slug: "orp-water-test-meter",
  },
  {
    name: "pH Water Testing Portable Meter",
    sku: "pH-MW-100",
    price: "$127.05",
    badge: "Testing Equipment",
    description: "Portable handy meter for testing water pH. Suitable for Educational, Agriculture and Horticulture as well as water and environmental analysis. 3x1x6 in, 3 lbs.",
    category: "Testing Equipment",
    image: "https://phprescription.com/wp-content/uploads/2020/12/pH-water-test-MW100-full-size.jpg",
    slug: "ph-water-testing-portable-meter",
  },
  // Replacement Parts
  {
    name: "Alkaline Triple Filter Replacement #5",
    sku: "UC-F-5",
    price: "$385.00",
    badge: "Replacement Parts",
    description: "Final stage of your pH Prescription drinking water system. Engineered with Crystal Technology to produce alkaline water, molecular hydrogen, negative ORP, and replenish essential minerals including calcium, magnesium, potassium and trace minerals.",
    category: "Replacement Parts",
    image: "https://phprescription.com/wp-content/uploads/2020/12/pH-UC-123-600x400.jpg",
    slug: "alkaline-triple-filter-replacement-5",
  },
  {
    name: "Taste and Odor Filter Replacement #6",
    sku: "IC-F-6",
    price: "$38.50",
    badge: "Replacement Parts",
    description: "Provides a polished finale to your water by eliminating post carbon taste and other odors.",
    category: "Replacement Parts",
    image: "https://phprescription.com/wp-content/uploads/2021/01/ICF-10-full-size-600x600.jpg",
    slug: "taste-and-odor-filter-replacement-6",
  },
  {
    name: "Ultimate Water Purification Membrane Replacement",
    sku: "GPD-75-4",
    price: "$176.00",
    badge: "Replacement Parts",
    description: "Quality water system high recovery membrane for maximum pressure PSI: 125PSI. 15x3x3 in, 1.75 lbs.",
    category: "Replacement Parts",
    image: "https://phprescription.com/wp-content/uploads/2020/12/GRO-75EN-full-size-600x600.jpg",
    slug: "ultimate-water-purification-membrane-replacement",
  },
  // Business Stations
  {
    name: "Premium Hydration Station",
    sku: "pHP-WC-PHS-Moderna4",
    price: "$3,495.00",
    badge: "Business Stations",
    description: "Premium commercial hydration station. 15x18x45 in, 77 lbs. Lease and finance options available for offices, gyms and corporate environments.",
    category: "Business Stations",
    image: "https://phprescription.com/wp-content/uploads/slider28/phs-info-with-logo.jpeg",
    slug: "premium-hydration-station",
  },
  {
    name: "Total Business Paddle-Touch Hot/Cold",
    sku: "WC-PP-6",
    price: "$2,613.60 – $3,484.80",
    badge: "Business Stations",
    description: "High-capacity hot/cold water cooler with paddle-touch dispensing. 14x14x48 in, 80 lbs. Lease and finance options available.",
    category: "Business Stations",
    image: "https://phprescription.com/wp-content/uploads/2021/04/TW56030-600x900.jpg",
    slug: "total-business-paddle-touch-hot-cold",
  },
  // Marine & Pool
  {
    name: "Marine Water System",
    sku: "",
    price: "Call for pricing",
    badge: "Marine & Pool",
    description: "Advanced marine water filtration system for vessels and coastal facilities. Handles saltwater and brackish water environments with proprietary mineral-reduction media.",
    category: "Marine & Pool",
    image: "https://phprescription.com/wp-content/uploads/2021/01/fpo_yacht_small.jpg",
    slug: "marine-water-system",
  },
  {
    name: "Pool Water Treatment System",
    sku: "",
    price: "Call for pricing",
    badge: "Marine & Pool",
    description: "Advanced pool and spa water treatment. Reduces chlorine demand by 25-40% while improving water clarity and guest comfort. Integrates with existing pool circulation systems.",
    category: "Marine & Pool",
    image: "https://phprescription.com/wp-content/uploads/2020/12/water-ripples-600x343.jpg",
    slug: "pool-water-treatment-system",
  },
  // Other
  {
    name: "Flojet Bottled Water Pump",
    sku: "pH-FJP",
    price: "$253.00",
    badge: "Other",
    description: "Portable versatile water pump that mounts easily. Ideal for large bottled water, events, family gatherings when access to water is limited. 8x4x5 in, 3 lbs.",
    category: "Other",
    image: "https://phprescription.com/wp-content/uploads/2020/12/flojet-pump-full-size-600x600.jpg",
    slug: "flojet-bottled-water-pump",
  },
  {
    name: "Compact Dual Filtration System",
    sku: "pH-WH-CDFS",
    price: "$1,899.50",
    badge: "Other",
    description: "Powerful compact twin-tanks filter that fits in small spaces. Carbon-block filtration removes up to 99% of chlorine, natural organic compounds, taste and odor compounds, and synthetic organic chemicals.",
    category: "Other",
    image: "https://phprescription.com/wp-content/uploads/2022/04/pH-WH-CDFS-featured-600x711.jpg",
    slug: "compact-dual-filtration-system",
  },
];

export const DOCTORS = [
  {
    name: "Dr. Mark A. Breiner, DDS",
    credential: "Author of Whole Body Dentistry",
    specialty: "Holistic Dentistry",
  },
  {
    name: "Dr. Debra DeMarta, MD, FACS",
    credential: "Board-Certified Colorectal Surgeon",
    specialty: "Colorectal Surgery",
  },
  {
    name: "Dr. Jerry Tennant, MD",
    credential: "Author of Healing is Voltage",
    specialty: "Integrative Medicine",
  },
  {
    name: "Steve Evans, DDS",
    credential: "Dental Practitioner",
    specialty: "Dentistry",
  },
  {
    name: "Dr. Nathan Bryan, PhD",
    credential: "Molecular Medicine Researcher",
    specialty: "Molecular Hydrogen Research",
  },
  {
    name: "Dr. Josh Axe, DC, DNM, CNS",
    credential: "Clinical Nutritionist",
    specialty: "Natural Medicine",
  },
  {
    name: "Dr. Walter Gil, M.D.",
    credential: "Medical Doctor",
    specialty: "Medicine",
  },
] as const;
